---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cli-persistent
      app.kubernetes.io/instance: cli
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cli-persistent
        app.kubernetes.io/instance: cli
    spec:
      volumes:
        - name: nginx
          persistentVolumeClaim:
            claimName: nginx
      enableServiceLinks: false
      securityContext:
        {}
      containers:
            - image: aronot/cli:1.0 
          name: cli
          securityContext:
            {}
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "cli"
          envFrom:
            - configMapRef:
                name: lagoon-env
          volumeMounts:
            - name: nginx
              mountPath: "/app/web/sites/default/files/"
          resources:
            {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nginx"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
